print("Knowledge is power!\n")
print("Knowledge")
print("is")
print("power!\n")
print("========================")
print("|                      |")
print("| Knowledge is power!  |")
print("|                      |")
print("========================")